name: KDoc Check

on: pull_request

jobs:
  kdoc-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Fetch base branch
        run: |
          BASE_BRANCH=${{ github.base_ref }}
          git fetch origin $BASE_BRANCH

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Run KDoc check script
        run: python kdoc_check.py
        env:
          BASE_BRANCH: ${{ github.base_ref }}
