name: KDoc Check

on: pull_request

jobs:
  kdoc-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch (master)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0 

      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Run KDoc check script
        run: python kdoc_check.py
        env:
          BASE_BRANCH: ${{ github.base_ref }}
